# Generated by Django 5.1.2 on 2025-06-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.JSONField()),
                ('colors', models.URLField(blank=True, null=True)),
                ('icons', models.CharField(max_length=200)),
                ('githubUrl', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
