# Generated by Django 5.1.2 on 2025-06-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectssection',
            old_name='colors',
            new_name='github_Url',
        ),
        migrations.RenameField(
            model_name='projectssection',
            old_name='githubUrl',
            new_name='image_url',
        ),
    ]
