# Generated by Django 5.1.2 on 2025-06-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
