# Generated by Django 5.1.2 on 2025-06-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_delete_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=200)),
                ('skills', models.JSONField()),
            ],
        ),
    ]
