# Generated by Django 5.1.2 on 2025-06-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_skilllists'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllists',
            name='icons',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
