# Generated by Django 5.1.2 on 2025-06-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_skilllists_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllists',
            name='icons',
            field=models.CharField(max_length=200),
        ),
    ]
