# Generated by Django 5.1.2 on 2025-06-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_alter_skilllists_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllists',
            name='icons',
        ),
        migrations.AddField(
            model_name='skilllists',
            name='icons_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
